### ISSUE TITLE
Example code?

### ISSUE THREAD

**Issue by hpssjellis** [DanielKalicki/RPLidar_Arduino#1]
Hi @DanielKalicki do you have example code that works with this library? I have the [D100 LD14](https://www.ldrobot.com/product/en/124) Lidar from ldrobot and the original [rplidar](https://github.com/robopeak/rplidar_arduino/tree/master/RPLidarDriver) library just prints useless data. Surprised it prints anything, put the output does not make much sense. I am working with the Arduino PortentaH7 which has Serial1 pins so your library might easily work.

**Comment by DanielKalicki** [comment]
The simplest way to test my library would be to import [RPLidar_Arduino](https://github.com/DanielKalicki/RPLidar_Arduino/tree/main)/[rplidar/rplidar.ino](https://github.com/DanielKalicki/RPLidar_Arduino/tree/main/rplidar/rplidar.ino) into Arduino Studio. 

Please change the scan type to Standard:
`#define SCAN_TYPE_STD` in line 33/34 instead of `SCAN_TYPE_EXPRESS`. This change will make the sampling rate lower but it reduces the transmission complexity - so should work out of the box.

Additionally please update the Serial output pinout in [RPLidar_Arduino](https://github.com/DanielKalicki/RPLidar_Arduino/tree/main)/[rplidar/rplidar_driver.cpp](https://github.com/DanielKalicki/RPLidar_Arduino/tree/main/rplidar/rplidar_driver.cpp) - lines 84-86.
`const int lidarRxPin = 34;`
`const int lidarTxPin = 33;`
`#define lidarSerial Serial5`

**Comment by hpssjellis** [comment]
@DanielKalicki Thanks you, for some reason I assumed rplidar.ino was the entry point of your library, not an example of how to use it. This makes so much more sense. I will see if I can get it running.

My Arduino forum about the lidar is at    https://forum.arduino.cc/t/portentah7-d100-lidar-by-ldrobot-and-grayscale-oled/1124747
